'atlas data: patch':
- changed-files:
  - any-glob-to-any-file: data/patches/**

'atlas data: direct':
- changed-files:
  - any-glob-to-any-file: web/atlas.json

staging merge:
- all:
  - base-branch: "master"
  - head-branch: 
    - "^cleanup$"
    - "^staging/.+$"